<?php

function firstmod_schema() {
  $schema['dic_data'] = array(
    'fields' => array(
      'id'=>array(
        'type'=>'serial',
        'not null' => TRUE,
      ),
      'fname'=>array(
        'type' => 'varchar_ascii',
        'length' => 40,
        'not null' => TRUE,
      ),
      'lname'=>array(
        'type' => 'varchar_ascii',
        'length' => 40,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );

  return $schema;

}